#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key       
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCypM//21mvBrcVt1tGwHOCvIGyrKdMEnflGQp66760FX1Pgp39HsasWFyEYFEkaXwuue3nvxGJnme+LsmWHGRzFQd+QO7GKqwhIhQ/U0+e0ZpEJMpOfOtEK+wOFKLygwQEtpTOmyAfgO5UmTalLj2Da4CMbURtvGBEPjxJketlrhaFtSFPjIxYUEUT1E7QE2KiQxg+ELkCkaqZOok9D4WsMD6HCkUfvUaAOBuVSwH3BVPQCS85TtY5uzlLE7tvL7lsEL2rTeRlhUK003jFSMxVvkQdA9aH2jGD+dM2raVt9TYHRyKzPEePjzljvvei5MbHrmwOpFUB0/EB5Z0BH48J aws-key
ssh_pwauth: false
disable_root: false 
package_update: true
packages:
  - php
  - mariadb-server
  - php-mysqli
  - wget
  - curl
write_files:
- content: | 
    <html>
      <head></head>
      <body>
      Diese Seite macht eine Abfrage auf die Datenbank. <br />
      Das ausgeführte Query ist: <i>select Host, User from mysql.user;</i><br /><br />
      Das Resultat: <br />
      <?php
              //database
              $servername = "127.0.0.1";
              $username = "admin";
              $password = "123";
              $dbname = "mysql";

              // Create connection
              $conn = new mysqli($servername, $username, $password, $dbname);
              // Check connection
              if ($conn->connect_error) {
                      die("Connection failed: " . $conn->connect_error);
              }

              $sql = "select Host, User from mysql.user;";
              $result = $conn->query($sql);
              while($row = $result->fetch_assoc()){
                      echo("<li>" . $row["Host"] . " / " . $row["User"] . "</li>");
              }
              //var_dump($result);
      ?>
      </body>
    </html>
  path: /var/www/html/db.php
  permissions: '0644'
- content: |
    <?php

    // Show all information, defaults to INFO_ALL
    phpinfo();

    ?>
  path: /var/www/html/info.php
  permissions: '0644'
runcmd:
  - sudo mysql -sfu root -e "CREATE USER IF NOT EXISTS 'admin'@'%' IDENTIFIED BY '123';"
  - sudo mysql -sfu root -e "GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' WITH GRANT OPTION;"
  - sudo mysql -sfu root -e "FLUSH PRIVILEGES;"
  - sudo systemctl restart mariadb.service
  - sudo sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/mariadb.conf.d/50-server.cnf | cat
  - sudo systemctl restart mariadb.service