#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key       
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCypM//21mvBrcVt1tGwHOCvIGyrKdMEnflGQp66760FX1Pgp39HsasWFyEYFEkaXwuue3nvxGJnme+LsmWHGRzFQd+QO7GKqwhIhQ/U0+e0ZpEJMpOfOtEK+wOFKLygwQEtpTOmyAfgO5UmTalLj2Da4CMbURtvGBEPjxJketlrhaFtSFPjIxYUEUT1E7QE2KiQxg+ELkCkaqZOok9D4WsMD6HCkUfvUaAOBuVSwH3BVPQCS85TtY5uzlLE7tvL7lsEL2rTeRlhUK003jFSMxVvkQdA9aH2jGD+dM2raVt9TYHRyKzPEePjzljvvei5MbHrmwOpFUB0/EB5Z0BH48J aws-key
ssh_pwauth: false
disable_root: false 
package_update: true
packages:
  - curl 
  - wget 
  - php
  - libapache2-mod-php
  - mariadb-server
  - php-mysqli
  - git
  - apache2
  - adminer
runcmd:
  - sudo mysql -sfu root -e "CREATE USER IF NOT EXISTS 'admin'@'%' IDENTIFIED BY '123';"
  - sudo mysql -sfu root -e "GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' WITH GRANT OPTION;"
  - sudo mysql -sfu root -e "FLUSH PRIVILEGES;"
  - sudo systemctl restart mariadb.service
  - git clone https://gitlab.com/ch-tbz-it/Stud/m346/m346scripts.git
  - sudo cp ./m346scripts/KN03/*.php /var/www/html/
  - sudo sed -i 's/???/123/g' /var/www/html/db.php | cat
  - sudo sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/mariadb.conf.d/50-server.cnf | cat
  - sudo a2enconf adminer
  - sudo systemctl restart mariadb.service
  - sudo systemctl restart apache2